baseURL: https://zsrobinson.com/
languageCode: en-us
title: Zachary Robinson
theme: "PaperMod"

enableRobotsTXT: true

params:
    env: production

    profileMode:
        enabled: false
        title: "Zachary Robinson" # optional default will be site title
        subtitle: "Hi, I'm a high school student interested in programming, networking, and cybersecurity."
        imageUrl: "/profile-picture/gravatar-256.jpg"
        imageTitle: "Profile Picture"
        imageWidth: 256
        imageHeight: 256
        buttons:
            - name: View Blog Posts
              url: "/posts"

    homeInfoParams:
        Title: Zachary Robinson
        Content: Hi there, my name is Zach. I'm a high school student interested in programming, networking, and cybersecurity. While the Internet as a whole may have moved on from blogging around a decade ago, I still wanted a place to showcase some of my projects and writing.

    socialIcons:
        - name: "github"
          url: "https://www.github.com/zsrobinson"
        - name: "instagram"
          url: "https://www.instagram.com/zsrobinson/"
        - name: "email"
          url: "mailto:contact@zsrobinson.com"

    assets:
        favicon: "/favicon/favicon.ico"
        favicon16x16: "/favicon/favicon-16x16.png"
        favicon32x32: "/favicon/favicon-32x32.png"
        apple_touch_icon: "/favicon/apple-touch-icon.png"
        # safari_pinned_tab: ""

    defaultTheme: dark
    # disableThemeToggle: false
    # ShowShareButtons: true
    ShowReadingTime: true
    ShowPostNavLinks: false # next and previous post buttons
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    disableAnchoredHeadings: true

    editPost:
        URL: "https://github.com/zsrobinson/blog/tree/main/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

menu:
    main:
        - name: Posts
          url: posts/
          weight: 1
        - name: Archive
          url: archives/
          weight: 5
        - name: Tags
          url: tags/
          weight: 10
        - name: Search
          url: search/
          weight: 15
        # - name: Categories
        #   url: categories/
        #   weight: 10

outputs:
    home:
        - HTML
        - JSON
        - RSS
